# Generated by Django 5.2 on 2025-04-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('acousticness', models.FloatField(blank=True, null=True)),
                ('instrumentalness', models.FloatField(blank=True, null=True)),
                ('liveness', models.FloatField(blank=True, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('num_bars', models.IntegerField(blank=True, null=True)),
                ('num_sections', models.IntegerField(blank=True, null=True)),
                ('num_segments', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
